1.1.0-STABLE
- Added support for symmetrical encryption (https://github.com/nozel-org/freebsd-backupbot/issues/9).

diff --git a/backupbot b/backupbot
--- a/backupbot
+++ b/backupbot
@@ -1,11 +1,11 @@
 #!/bin/sh
 
 ################################################################################
-# Version 1.0.0-STABLE (01-07-2020)
+# Version 1.1.0-STABLE (19-01-2021)
 ################################################################################
 
 ################################################################################
-# Copyright 2019-2020 Nozel/Sebas Veeke. Licenced under a Creative Commons
+# Copyright 2019-2021 Nozel/Sebas Veeke. Licenced under a Creative Commons
 # Attribution-NonCommercial-ShareAlike 4.0 International License.
 #
 # See https://creativecommons.org/licenses/by-nc-sa/4.0/
@@ -20,7 +20,7 @@
 ################################################################################
 
 # serverbot version
-BACKUPBOT_VERSION='1.0.0'
+BACKUPBOT_VERSION='1.1.0'
 
 # backupbot parameters can be configured in /usr/local/etc/backupbot.conf
 # if the backupbot configuration file exists, it gets sourced by backupbot
@@ -28,6 +28,8 @@ if [ -f /usr/local/etc/backupbot.conf ]; then
     # populate all usable variables for checking validity later on
     AUTOMATIC_BACKUP_ENABLE='0'
     AUTOMATIC_BACKUP_CRON='0'
+    BACKUP_ENCRYPTION='0'
+    BACKUP_ENCRYPTION_SECRET='0'
     BACKUP_FILES_ENABLE='0'
     BACKUP_FILES_PREFIX='0'
     BACKUP_FILES_RETENTION='0'
@@ -51,6 +53,7 @@ if [ -f /usr/local/etc/backupbot.conf ]; then
 else
     # if backupbot.conf does not exist, return this error 
     echo 'backupbot: error: /usr/local/etc/backupbot.conf is required but cannot be found'
+    exit 1
 fi
 
 ################################################################################
@@ -116,7 +119,7 @@ error_no_root_privileges() {
 }
 
 error_os_not_supported() {
-    echo 'sparry: operating system is not supported.'
+    echo 'backupbot: operating system is not supported'
     exit 1
 }
 
@@ -148,6 +151,12 @@ error_retention_not_integer() {
 
 error_feature_not_configured() {
     echo 'backupbot: error: one of the invoked features is not configured in /usr/local/etc/backupbot.conf'
+    exit 1
+}
+
+error_gpg_not_installed() {
+    echo 'backupbot: error: gpg is required but not installed'
+    echo 'backupbot: install gpg with "pkg install gnupg"'
     exit 1
 }
 
@@ -199,7 +208,7 @@ requirement_os() {
 }
 
 ################################################################################
-# OPTION FUNCTIONS
+# GENERAL FUNCTIONS
 ################################################################################
 
 option_version() {
@@ -243,24 +252,54 @@ option_cron() {
 ################################################################################
 
 feature_files() {
-    # backupbot uses tar for archiving data and xz for compressing data
+    # backupbot uses tar for archiving data, xz for compressing data and gpg for encryption
     if [ "${BACKUP_FILES_ENABLE}" = 'YES' ]; then
-        # the following settings are used for tar:
-        # --create               (-c) create new archive containing the specified items
-        # --xz                   (-J) compress the resulting archive with xz
-        # --preserve-permissions (-p) preserve file permissions
-        # --file                 (-f) write the archive to the specified file
-        # --verbose              (-v) produce verbose output (disabled by default)
-        tar --create --preserve-permissions --xz --file "${BACKUP_FILES_DESTINATION}/${BACKUP_FILES_PREFIX}-files.tar.xz" ${BACKUP_FILES}
+        if [ "${BACKUP_ENCRYPTION}" = 'YES' ]; then
+            if command -v gpg >/dev/null 2>&1; then
+                # the following settings are used for tar:
+                # --create               (-c) create new archive containing the specified items
+                # --preserve-permissions (-p) preserve file permissions
+                # --xz                   (-J) compress the resulting archive with xz
+                # --file -               (-f) pipe the archive to next command
+                # --verbose              (-v) produce verbose output (disabled by default)
+                # the following settings are used for gpg:
+                # --symmetric            (-c) use symmetric cipher for encryption
+                # --cipher-algo AES256        use AES256 as cipher algorithm
+                # --batch                     non-interactive mode
+                # --passphrase                use password provided in backupbot.conf
+                # --output               (-o) write output to file
+                tar --create --preserve-permissions --xz --file - ${BACKUP_FILES} | gpg --symmetric --cipher-algo AES256 --batch --passphrase "${BACKUP_ENCRYPTION_SECRET}" > "${BACKUP_FILES_DESTINATION}/${BACKUP_FILES_PREFIX}-files.tar.xz.gpg"
+            else
+                error_gpg_not_installed
+            fi
+        else
+            # the following settings are used for tar:
+            # --create               (-c) create new archive containing the specified items
+            # --preserve-permissions (-p) preserve file permissions
+            # --xz                   (-J) compress the resulting archive with xz
+            # --file                 (-f) write the archive to the specified file
+            # --verbose              (-v) produce verbose output (disabled by default)
+            tar --create --preserve-permissions --xz --file "${BACKUP_FILES_DESTINATION}/${BACKUP_FILES_PREFIX}-files.tar.xz" ${BACKUP_FILES}
+        fi
     fi
 }
 
 feature_mysql() {
     # create a list of all user created mysql databases and mysqldump them to their own compressed (xz) file
     if [ "${BACKUP_MYSQL_ENABLE}" = 'YES' ]; then
-        for DB in $(mysql -e 'show databases' -s --skip-column-names | sed '/performance_schema/d' | sed '/information_schema/d' | sed '/mysql/d'); do
-            mysqldump --single-transaction "${DB}" | xz > "${BACKUP_MYSQL_DESTINATION}/${BACKUP_MYSQL_PREFIX}-${DB}.sql.xz"
-        done
+        if [ "${BACKUP_ENCRYPTION}" = 'YES' ]; then
+            if command -v gpg >/dev/null 2>&1; then
+                for DB in $(mysql -e 'show databases' -s --skip-column-names | sed '/performance_schema/d' | sed '/information_schema/d' | sed '/mysql/d'); do
+                    mysqldump --single-transaction "${DB}" | xz | gpg --symmetric --cipher-algo AES256 --batch --passphrase "${BACKUP_ENCRYPTION_SECRET}" > "${BACKUP_MYSQL_DESTINATION}/${BACKUP_MYSQL_PREFIX}-${DB}.sql.xz.gpg"
+                done
+            else
+                error_gpg_not_installed
+            fi
+        else    
+            for DB in $(mysql -e 'show databases' -s --skip-column-names | sed '/performance_schema/d' | sed '/information_schema/d' | sed '/mysql/d'); do
+                mysqldump --single-transaction "${DB}" | xz > "${BACKUP_MYSQL_DESTINATION}/${BACKUP_MYSQL_PREFIX}-${DB}.sql.xz"
+            done
+        fi
     fi
 }
 
