1.3.0-RELEASE
- Added more compression alternatives: no compression, gzip, bzip2 and xz https://github.com/nozel-org/freebsd-backupbot/issues/4.

diff --git a/backupbot b/backupbot
--- a/backupbot
+++ b/backupbot
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 ################################################################################
-# Version 1.2.2-RELEASE (14-01-2022)
+# Version 1.3.0-RELEASE (15-01-2022)
 ################################################################################
 
 ################################################################################
@@ -20,7 +20,7 @@
 ################################################################################
 
 # serverbot version
-BACKUPBOT_VERSION='1.2.2'
+BACKUPBOT_VERSION='1.3.0'
 
 # backupbot parameters can be configured in /usr/local/etc/backupbot.conf
 # if the backupbot configuration file exists, it gets sourced by backupbot
@@ -33,11 +33,13 @@ if [ -f /usr/local/etc/backupbot.conf ]; then
     BACKUP_FILES_ENABLE='0'
     BACKUP_FILES_PREFIX='0'
     BACKUP_FILES_RETENTION='0'
+    BACKUP_FILES_COMPRESSION='0'
     BACKUP_FILES_DESTINATION='0'
     BACKUP_FILES='0'
     BACKUP_MYSQL_ENABLE='0'
     BACKUP_MYSQL_PREFIX='0'
     BACKUP_MYSQL_RETENTION='0'
+    BACKUP_MYSQL_COMPRESSION='0'
     BACKUP_MYSQL_DESTINATION='0'
 
     # and source backupbot.conf
@@ -160,6 +162,11 @@ error_gpg_not_installed() {
     exit 1
 }
 
+error_compression_not_configured() {
+    echo 'backupbot: error: compression is not configured properly in /usr/local/etc/backupbot.conf'
+    exit 1
+}
+
 ################################################################################
 # REQUIREMENT FUNCTIONS
 ################################################################################
@@ -191,6 +198,10 @@ requirement_argument_validity() {
     if ! [ "${BACKUP_MYSQL_RETENTION}" -eq "${BACKUP_MYSQL_RETENTION}" ] 2> /dev/null; then
         error_retention_not_integer
     fi
+    # compression feature number must be 0, 2, 3 or 4
+    if [ "${BACKUP_FILES_COMPRESSION}" != '0' ] && [ "${BACKUP_FILES_COMPRESSION}" != '1' ] && [ "${BACKUP_FILES_COMPRESSION}" != '2' ] && [ "${BACKUP_FILES_COMPRESSION}" != '3' ]; then
+        error_compression_not_configured
+    fi
 }
 
 requirement_root() {
@@ -204,6 +215,13 @@ requirement_os() {
     # show error when freebsd-version cannot be found
     if [ ! "$(command -v freebsd-version)" ]; then
         error_os_not_supported
+    fi
+}
+
+requirement_gpg() {
+    # show error when gpg cannot be found
+    if [ ! "$(command -v gpg)" ]; then
+        error_gpg_not_installed
     fi
 }
 
@@ -251,68 +269,105 @@ option_cron() {
 # FEATURE FUNCTIONS
 ################################################################################
 
+# the following settings are used for tar:
+# --create               (-c) create new archive containing the specified items
+# --preserve-permissions (-p) preserve file permissions
+# --gzip                 (-z) compress the resulting archive with gunzip
+# --bzip2                (-j) compress the resulting archive with bzip2
+# --xz                   (-J) compress the resulting archive with xz
+# --file -               (-f) pipe the archive to next command
+# --verbose              (-v) produce verbose output (disabled by default)
+
+# the following settings are used for gpg:
+# --symmetric            (-c) use symmetric cipher for encryption
+# --cipher-algo AES256        use AES256 as cipher algorithm
+# --batch                     non-interactive mode
+# --passphrase                use password provided in backupbot.conf
+# --output               (-o) write output to file
+
+# the following settings are used for mysqldump
+# --single-transaction        dumps all tables in a single transaction
+
 feature_files() {
-    # backupbot uses tar for archiving data, xz for compressing data and gpg for encrypting data
     if [ "${BACKUP_FILES_ENABLE}" = 'YES' ]; then
-        if [ "${BACKUP_ENCRYPTION}" = 'YES' ]; then
-            # check whether gpg is available
-            if command -v gpg >/dev/null 2>&1; then
-                # the following settings are used for tar:
-                # --create               (-c) create new archive containing the specified items
-                # --preserve-permissions (-p) preserve file permissions
-                # --xz                   (-J) compress the resulting archive with xz
-                # --file -               (-f) pipe the archive to next command
-                # --verbose              (-v) produce verbose output (disabled by default)
-                # the following settings are used for gpg:
-                # --symmetric            (-c) use symmetric cipher for encryption
-                # --cipher-algo AES256        use AES256 as cipher algorithm
-                # --batch                     non-interactive mode
-                # --passphrase                use password provided in backupbot.conf
-                # --output               (-o) write output to file
-                tar --create --preserve-permissions --xz --file - ${BACKUP_FILES} | gpg --symmetric --cipher-algo AES256 --batch --passphrase "${BACKUP_ENCRYPTION_SECRET}" > "${BACKUP_FILES_DESTINATION}/${BACKUP_FILES_PREFIX}-files.tar.xz.gpg"
-            else
-                error_gpg_not_installed
-            fi
-        else
-            # the following settings are used for tar:
-            # --create               (-c) create new archive containing the specified items
-            # --preserve-permissions (-p) preserve file permissions
-            # --xz                   (-J) compress the resulting archive with xz
-            # --file                 (-f) write the archive to the specified file
-            # --verbose              (-v) produce verbose output (disabled by default)
-            tar --create --preserve-permissions --xz --file "${BACKUP_FILES_DESTINATION}/${BACKUP_FILES_PREFIX}-files.tar.xz" ${BACKUP_FILES}
+        # check configured backup compression and create variables for arguments and file extension
+        if [ "${BACKUP_FILES_COMPRESSION}" = '0' ]; then
+            TAR_COMPRESSION_ARGUMENT=''
+            FILES_FILE_EXTENSION='tar'
+        elif [ "${BACKUP_FILES_COMPRESSION}" = '1' ]; then
+            TAR_COMPRESSION_ARGUMENT='--gzip'
+            FILES_FILE_EXTENSION='tar.gz'
+        elif [ "${BACKUP_FILES_COMPRESSION}" = '2' ]; then
+            TAR_COMPRESSION_ARGUMENT='--bzip2'
+            FILES_FILE_EXTENSION='tar.bz2'
+        elif [ "${BACKUP_FILES_COMPRESSION}" = '3' ]; then
+            TAR_COMPRESSION_ARGUMENT='--xz'
+            FILES_FILE_EXTENSION='tar.xz'
         fi
+
+        # check whether backup encryption is enabled
+        if [ "${BACKUP_ENCRYPTION}" = 'YES' ]; then
+            requirement_gpg
+            tar --create --preserve-permissions ${TAR_COMPRESSION_ARGUMENT} --file - ${BACKUP_FILES} | gpg --symmetric --cipher-algo AES256 --batch --passphrase "${BACKUP_ENCRYPTION_SECRET}" > "${BACKUP_FILES_DESTINATION}/${BACKUP_FILES_PREFIX}-files.${FILES_FILE_EXTENSION}.gpg"
+        else
+            tar --create --preserve-permissions ${TAR_COMPRESSION_ARGUMENT} --file "${BACKUP_FILES_DESTINATION}/${BACKUP_FILES_PREFIX}-files.${FILES_FILE_EXTENSION}" ${BACKUP_FILES}
+        fi
+
         # delete backups older than file retention, unless it's zero (infinite)
         if [ "${BACKUP_FILES_RETENTION}" -gt '0' ]; then
-            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*.tar.xz' -delete
-            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*.tar.xz.gpg' -delete
+            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar' -delete
+            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar.gz' -delete
+            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar.bz2' -delete
+            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar.xz' -delete
+            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar.gpg' -delete
+            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar.gz.gpg' -delete
+            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar.bz2.gpg' -delete
+            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar.xz.gpg' -delete
         fi
     fi
 }
 
 feature_mysql() {
-    # backupbot uses tar for archiving data, xz for compressing data and gpg for encrypting data
     if [ "${BACKUP_MYSQL_ENABLE}" = 'YES' ]; then
+        # check configured backup compression and create variables for arguments and file extension
+        if [ "${BACKUP_MYSQL_COMPRESSION}" = '0' ]; then
+            MYSQL_COMPRESSION_ARGUMENT='cat'
+            MYSQL_FILE_EXTENSION='sql'
+        elif [ "${BACKUP_MYSQL_COMPRESSION}" = '1' ]; then
+            MYSQL_COMPRESSION_ARGUMENT='gzip'
+            MYSQL_FILE_EXTENSION='sql.gz'
+        elif [ "${BACKUP_MYSQL_COMPRESSION}" = '2' ]; then
+            MYSQL_COMPRESSION_ARGUMENT='bzip2'
+            MYSQL_FILE_EXTENSION='sql.bz2'
+        elif [ "${BACKUP_MYSQL_COMPRESSION}" = '3' ]; then
+            MYSQL_COMPRESSION_ARGUMENT='xz'
+            MYSQL_FILE_EXTENSION='sql.xz'
+        fi
+
+        # check whether backup encryption is enabled
         if [ "${BACKUP_ENCRYPTION}" = 'YES' ]; then
-            # check whether gpg is available
-            if command -v gpg >/dev/null 2>&1; then
-                # create a list of all user created mysql databases and mysqldump them to their own encrypted and compressed (xz.gpg) file
-                for DB in $(mysql -e 'show databases' -s --skip-column-names | sed '/performance_schema/d' | sed '/information_schema/d' | sed '/mysql/d'); do
-                    mysqldump --single-transaction "${DB}" | xz | gpg --symmetric --cipher-algo AES256 --batch --passphrase "${BACKUP_ENCRYPTION_SECRET}" > "${BACKUP_MYSQL_DESTINATION}/${BACKUP_MYSQL_PREFIX}-${DB}.sql.xz.gpg"
-                done
-            else
-                error_gpg_not_installed
-            fi
-        else
-            # create a list of all user created mysql databases and mysqldump them to their own compressed (xz) file
+            requirement_gpg
+            # create a list of all user created mysql databases and mysqldump them to their own file
             for DB in $(mysql -e 'show databases' -s --skip-column-names | sed '/performance_schema/d' | sed '/information_schema/d' | sed '/mysql/d'); do
-                mysqldump --single-transaction "${DB}" | xz > "${BACKUP_MYSQL_DESTINATION}/${BACKUP_MYSQL_PREFIX}-${DB}.sql.xz"
+                mysqldump --single-transaction "${DB}" | ${MYSQL_COMPRESSION_ARGUMENT} | gpg --symmetric --cipher-algo AES256 --batch --passphrase "${BACKUP_ENCRYPTION_SECRET}" > "${BACKUP_MYSQL_DESTINATION}/${BACKUP_MYSQL_PREFIX}-${DB}.${MYSQL_FILE_EXTENSION}.gpg"
+            done
+        else
+            # create a list of all user created mysql databases and mysqldump them to their own file
+            for DB in $(mysql -e 'show databases' -s --skip-column-names | sed '/performance_schema/d' | sed '/information_schema/d' | sed '/mysql/d'); do
+                mysqldump --single-transaction "${DB}" | ${MYSQL_COMPRESSION_ARGUMENT} > "${BACKUP_MYSQL_DESTINATION}/${BACKUP_MYSQL_PREFIX}-${DB}.${MYSQL_FILE_EXTENSION}"
             done
         fi
+
         # delete backups older than mysql retention, unless it's zero (infinite)
         if [ "${BACKUP_MYSQL_RETENTION}" -gt '0' ]; then
-            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*.sql.xz' -delete
-            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*.sql.xz.gpg' -delete
+            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql' -delete
+            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql.gz' -delete
+            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql.bz2' -delete
+            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql.xz' -delete
+            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql.gpg' -delete
+            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql.gz.gpg' -delete
+            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql.bz2.gpg' -delete
+            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql.xz.gpg' -delete
         fi
     fi
 }
